const express = require("express");
const login = require("../controllers/login.js");
const { AdminAuthMiddleware } = require("../controllers/middleware.js");
const home = require("../controllers/home.js");
const getProductCategories = require("../controllers/getProductCategories.js");
const addProductCategory = require("../controllers/addProductCategory.js");
const updateProductCategory = require("../controllers/updateProductCategory.js");
const getProductCategoryById = require("../controllers/getProductCategoryById.js");
const delProductCategory = require("../controllers/delProductCategory.js");
const getProductDetails = require("../controllers/getProductDetails.js");
const addProductDetails = require("../controllers/addProductDetails.js");
const getProductDetailById = require("../controllers/getProductDetailById.js");
const updateProductDetails = require("../controllers/updateProductDetails.js");
const delProductDetails = require("../controllers/delProductDetails.js");
const getCustomers = require("../controllers/getCustomers.js");
const addCustomer = require("../controllers/addCustomer.js");
const updateCustomer = require("../controllers/updateCustomer.js");
const getCustomerById = require("../controllers/getCustomerById.js");
const delCustomer = require("../controllers/delCustomer.js");
const getPaymentsData = require("../controllers/getPaymentsData.js");
const getReceiptsData = require("../controllers/getReceiptsData.js");
const getPaymentById = require("../controllers/getPaymentById.js");
const delPayment = require("../controllers/delPayment.js");
const getInvoiceSeriesByType = require("../controllers/getInvoiceSeriesByType.js");
const addPayment = require("../controllers/addPayment.js");
const updatePayment = require("../controllers/updatePayment.js");
const getAccountGroupData = require("../controllers/getAccountGroupData.js");
const getAccountGroupById = require("../controllers/getAccountGroupById.js");
const delAccountGroup = require("../controllers/delAccountGroup.js");
const addAccountGroup = require("../controllers/addAccountGroup.js");
const updateAccountGroup = require("../controllers/updateAccountGroup.js");
const searchCustomersByInput = require("../controllers/searchCustomersByInput.js");
const addLedgerGroup = require("../controllers/addLedgerGroup.js");
const updateLedgerGroup = require("../controllers/updateLedgerGroup.js");
const getLedgerGroupData = require("../controllers/getLedgerGroupData.js");
const getLedgerGroupById = require("../controllers/getLedgerGroupById.js");
const delLedgerGroup = require("../controllers/delLedgerGroup.js");
const searchLedgersByInput = require("../controllers/searchLedgersByInput.js");
const getMopOptions = require("../controllers/getMopOptions.js");
const getReceiptById = require("../controllers/getReceiptById.js");
const delReceipt = require("../controllers/delReceipt.js");
const addReceipt = require("../controllers/addReceipt.js");
const updateReceipt = require("../controllers/updateReceipt.js");
const searchProductByInput = require("../controllers/searchProductByInput.js");
const getMopSettings = require("../controllers/getMopSettings.js");
const setMopSettings = require("../controllers/setMopSettings.js");
const addPurchaseInvoice = require("../controllers/addPurchaseInvoice.js");
const addSalesInvoice = require("../controllers/addSalesInvoice.js");
const getTrialBalanceSimpleData = require("../controllers/getTrialBalanceSimpleData.js");
const getTrialBalanceDetailedData = require("../controllers/getTrialBalanceDetailedData.js");
const getProfitAndLossSimpleData = require("../controllers/getProfitAndLossSimpleData.js");
const getProfitAndLossDetailedData = require("../controllers/getProfitAndLossDetailedData.js");
const getBalanceSheetSimpleData = require("../controllers/getBalanceSheetSimpleData.js");
const getBalanceSheetDetailedData = require("../controllers/getBalanceSheetDetailedData.js");
const getPurchaseDayBookData = require("../controllers/getPurchaseDayBookData.js");
const getPurchaseDayBookDetailData = require("../controllers/getPurchaseDayBookDetailData.js");
const getSalesDayBookData = require("../controllers/getSalesDayBookData.js");
const getSalesDayBookDetailData = require("../controllers/getSalesDayBookDetailData.js");
const getBanks = require("../controllers/getBanks.js");
const uploadCustomers = require("../controllers/uploadCustomers.js");
const uploadVendors = require("../controllers/uploadVendors.js");
const getOsByAccountCode = require("../controllers/getOsByAccountCode.js");
const getledgerReportData = require("../controllers/getledgerReportData.js");
const searchCustomerLedgersByInput = require("../controllers/searchCustomerLedgersByInput.js");
const getOutstandingCustomerData = require("../controllers/getOutstandingCustomerData.js");
const getInvoiceHeaderData = require("../controllers/getInvoiceHeaderData.js");
const getInvoiceItemsData = require("../controllers/getInvoiceItemsData.js");
const getInvoiceFooterData = require("../controllers/getInvoiceFooterData.js");
const getPaymentReportData = require("../controllers/getPaymentReportData.js");
const getReceiptReportData = require("../controllers/getReceiptReportData.js");
const internalLoginToFormat = require("../controllers/internalLoginToFormat.js");
const internalLoginToDelInvoice = require("../controllers/internalLoginToDelInvoice.js");
const uploadProductCategories = require("../controllers/uploadProductCategories.js");
const uploadProductDetails = require("../controllers/uploadProductDetails.js");
const getProfile = require("../controllers/getProfile.js");
const updateProfile = require("../controllers/updateProfile.js");
const changePassword = require("../controllers/changePassword.js");
const uploadLogo = require("../controllers/uploadLogo.js");
const addSalesOrderInvoice = require("../controllers/addSalesOrderInvoice.js");
const getSalesOrderDayBookData = require("../controllers/getSalesOrderDayBookData.js");
const getSalesOrderDayBookDetailData = require("../controllers/getSalesOrderDayBookDetailData.js");
const convertToSales = require("../controllers/convertToSales.js");
const addStore = require("../controllers/addStore.js");
const updateStore = require("../controllers/updateStore.js");
const getStoresData = require("../controllers/getStoresData.js");
const getStoreById = require("../controllers/getStoreById.js");
const delStore = require("../controllers/delStore.js");
const uploadStores = require("../controllers/uploadStores.js");
const getStores = require("../controllers/getStores.js");
const addStockTransferInvoice = require("../controllers/addStockTransferInvoice.js");
const getStockTransferHeaderData = require("../controllers/getStockTransferHeaderData.js");
const getStockTransferFooterData = require("../controllers/getStockTransferFooterData.js");
const getStockTransferItemsData = require("../controllers/getStockTransferItemsData.js");
const getStockTransferDayBookData = require("../controllers/getStockTransferDayBookData.js");
const getStockTransferDayBookDetailData = require("../controllers/getStockTransferDayBookDetailData.js");
const getStocksReportData = require("../controllers/getStocksReportData.js");
const searchStoresByInput = require("../controllers/searchStoresByInput.js");
const getPurchaseItemWiseData = require("../controllers/getPurchaseItemWiseData.js");
const getSalesItemWiseData = require("../controllers/getSalesItemWiseData.js");
const getSalesOrderItemWiseData = require("../controllers/getSalesOrderItemWiseData.js");
const getStockTransferItemWiseData = require("../controllers/getStockTransferItemWiseData.js");
const addRole = require("../controllers/addRole.js");
const updateRole = require("../controllers/updateRole.js");
const getRoles = require("../controllers/getRoles.js");
const getRoleById = require("../controllers/getRoleById.js");
const delRole = require("../controllers/delRole.js");
const uploadRoles = require("../controllers/uploadRoles.js");
const addUser = require("../controllers/addUser.js");
const updateUser = require("../controllers/updateUser.js");
const getUsers = require("../controllers/getUsers.js");
const getUserById = require("../controllers/getUserById.js");
const delUsers = require("../controllers/delUsers.js");
const uploadUsers = require("../controllers/uploadUsers.js");
const addPage = require("../controllers/addPage.js");
const updatePage = require("../controllers/updatePage.js");
const getPages = require("../controllers/getPages.js");
const getPageById = require("../controllers/getPageById.js");
const uploadPages = require("../controllers/uploadPages.js");
const getPermissionsById = require("../controllers/getPermissionsById.js");
const updatePermission = require("../controllers/updatePermission.js");
const uploadQRImage = require("../controllers/uploadQRImage.js");
const getSalesGraphData = require("../controllers/getSalesGraphData.js");
const searchAdmins = require("../controllers/searchAdmins.js");
const sendEmailOTP = require("../controllers/sendEmailOTP.js");
const verifyEmailOTP = require("../controllers/verifyEmailOTP.js");
const adminSignUp = require("../controllers/adminSignUp.js");
const getBarcodeSeries = require("../controllers/getBarcodeSeries.js");
const searchSalesProductByInput = require("../controllers/searchSalesProductByInput.js");
const searchBarcodeByInput = require("../controllers/searchBarcodeByInput.js");
const validateBarcodeInStock = require("../controllers/validateBarcodeInStock.js");
const searchUsername = require("../controllers/searchUsername.js");
const addOpeningStockInvoice = require("../controllers/addOpeningStockInvoice.js");
const getOpeningStockDayBookData = require("../controllers/getOpeningStockDayBookData.js");
const getOpeningStockDayBookDetailData = require("../controllers/getOpeningStockDayBookDetailData.js");
const getOpeningStockItemWiseData = require("../controllers/getOpeningStockItemWiseData.js");
const sendEmailLinkToResetPassword = require("../controllers/sendEmailLinkToResetPassword.js");
const sendPasswordToReset = require("../controllers/sendPasswordToReset.js");
const uploadProductItemsDetails = require("../controllers/uploadProductItemsDetails.js");
const uploadSalesProductItemsDetails = require("../controllers/uploadSalesProductItemsDetails.js");
const addImportStock = require("../controllers/addImportStock.js");
const searchUserByInput = require("../controllers/searchUserByInput.js");
const getCountries = require("../controllers/getCountries.js");
const getStates = require("../controllers/getStates.js");
const getCities = require("../controllers/getCities.js");
const getNextVerifiedInvoiceNo = require("../controllers/getNextVerifiedInvoiceNo.js");
const getOutstandingUserStatement = require("../controllers/getOutstandingUserStatement.js");
const addEstimateInvoice = require("../controllers/addEstimateInvoice.js");
const getEstimateDayBookData = require("../controllers/getEstimateDayBookData.js");
const getEstimateDayBookDetailData = require("../controllers/getEstimateDayBookDetailData.js");
const getEstimateItemWiseData = require("../controllers/getEstimateItemWiseData.js");
const getledgerSummarisedReportData = require("../controllers/getledgerSummarisedReportData.js");
const getledgerSummarisedBalanceSheetData = require("../controllers/getledgerSummarisedBalanceSheetData.js");
const getInvoiceSeriesForCustomer = require("../controllers/getInvoiceSeriesForCustomer.js");
const addDynamicColumns = require("../controllers/addDynamicColumns.js");
const getPriceLists = require("../controllers/getPriceLists.js");
const getPriceListById = require("../controllers/getPriceListById.js");
const delPriceList = require("../controllers/delPriceList.js");
const updateDynamicColumns = require("../controllers/updateDynamicColumns.js");
const updateAllProductDetails = require("../controllers/updateAllProductDetails.js");
const addPettySalesInvoice = require("../controllers/addPettySalesInvoice.js");
const getPettySalesDayBookData = require("../controllers/getPettySalesDayBookData.js");
const getPettySalesDayBookDetailData = require("../controllers/getPettySalesDayBookDetailData.js");
const getPettySalesItemWiseData = require("../controllers/getPettySalesItemWiseData.js");
const getReceiptByInvoiceNo = require("../controllers/getReceiptByInvoiceNo.js");
const getPaymentByInvoiceNo = require("../controllers/getPaymentByInvoiceNo.js");
const getOsByDefaultAccountCode = require("../controllers/getOsByDefaultAccountCode.js");
const searchProductCategoryByInput = require("../controllers/searchProductCategoryByInput.js");
const searchProductByProductCategoryByInput = require("../controllers/searchProductByProductCategoryByInput.js");
const getReceiptSplitsData = require("../controllers/getReceiptSplitsData.js");
const getPaymentSplitsData = require("../controllers/getPaymentSplitsData.js");
const getBillByBillCustomerData = require("../controllers/getBillByBillCustomerData.js");
const getBillByBillSupplierData = require("../controllers/getBillByBillSupplierData.js");
const getAgeingWiseOutstandingUserStatement = require("../controllers/getAgeingWiseOutstandingUserStatement.js");
const getStockHistoryReportData = require("../controllers/getStockHistoryReportData.js");
const addPurchaseReturnInvoice = require("../controllers/addPurchaseReturnInvoice.js");
const getPurchaseReturnDayBookData = require("../controllers/getPurchaseReturnDayBookData.js");
const getPurchaseReturnDayBookDetailData = require("../controllers/getPurchaseReturnDayBookDetailData.js");
const getPurchaseReturnItemWiseData = require("../controllers/getPurchaseReturnItemWiseData.js");
const addSalesReturnInvoice = require("../controllers/addSalesReturnInvoice.js");
const getSalesReturnDayBookData = require("../controllers/getSalesReturnDayBookData.js");
const getSalesReturnDayBookDetailData = require("../controllers/getSalesReturnDayBookDetailData.js");
const getSalesReturnItemWiseData = require("../controllers/getSalesReturnItemWiseData.js");
const getSalesReturnInvoiceData = require("../controllers/getSalesReturnInvoiceData.js");
const addProductionInvoice = require("../controllers/addProductionInvoice.js");
const searchBarcodeByInputForStocksReport = require("../controllers/searchBarcodeByInputForStocksReport.js");
const uploadCompanySealImage = require("../controllers/uploadCompanySealImage.js");
const uploadAuthorisedSignatureImage = require("../controllers/uploadAuthorisedSignatureImage.js");
const getProductCompositionData = require("../controllers/getProductCompositionData.js");
const getProductCompositionById = require("../controllers/getProductCompositionById.js");
const updateProductComposition = require("../controllers/updateProductComposition.js");
const addProductComposition = require("../controllers/addProductComposition.js");
const delProductComposition = require("../controllers/delProductComposition.js");
const uploadSalesReturnProductItemsDetails = require("../controllers/uploadSalesReturnProductItemsDetails.js");
const addAttendance = require("../controllers/addAttendance.js");
const deleteAttendance = require("../controllers/deleteAttendance.js");
const getAllAttendance = require("../controllers/getAllAttendance.js");
const updateAttendance = require("../controllers/updateAttendance.js");
const getSalaryBalance = require("../controllers/getSalaryBalance.js");
const addOrEditPrnFile = require("../controllers/addOrEditPrnfile")

const router = express.Router();
router.post("/login", login);

router.get("/home", AdminAuthMiddleware, home);
router.get("/getProductCategories", getProductCategories);
router.post("/addProductCategory", addProductCategory);
router.post("/updateProductCategory", updateProductCategory);
router.get("/getProductCategoryById", getProductCategoryById);
router.post("/delProductCategory", delProductCategory);
router.get("/getProductDetails", getProductDetails);
router.post("/addProductDetails", addProductDetails);
router.get("/getProductDetailById", getProductDetailById);
router.post("/updateProductDetails", updateProductDetails);
router.post("/delProductDetails", delProductDetails);
router.get("/getCustomers", getCustomers);
router.post("/addCustomer", addCustomer);
router.get("/getCustomerById", getCustomerById);
router.post("/updateCustomer", updateCustomer);
router.post("/delCustomer", delCustomer);
router.get("/getPaymentsData", getPaymentsData);
router.get("/getPaymentById", getPaymentById);
router.post("/delPayment", delPayment);
router.get("/getInvoiceSeriesByType", getInvoiceSeriesByType);
router.get("/getReceiptsData", getReceiptsData);
router.post("/addPayment", addPayment);
router.post("/updatePayment", updatePayment);
router.get("/getAccountGroupData", getAccountGroupData);
router.get("/getAccountGroupById", getAccountGroupById);
router.post("/delAccountGroup", delAccountGroup);
router.post("/addAccountGroup", addAccountGroup);
router.post("/updateAccountGroup", updateAccountGroup);
router.post("/searchCustomersByInput", searchCustomersByInput);
router.post("/addLedgerGroup", addLedgerGroup);
router.post("/updateLedgerGroup", updateLedgerGroup);
router.get("/getLedgerGroupData", getLedgerGroupData);
router.get("/getLedgerGroupById", getLedgerGroupById);
router.post("/delLedgerGroup", delLedgerGroup);
router.post("/searchLedgersByInput", searchLedgersByInput);
router.get("/getMopOptions", getMopOptions);
router.get("/getReceiptById", getReceiptById);
router.post("/delReceipt", delReceipt);
router.post("/addReceipt", addReceipt);
router.post("/updateReceipt", updateReceipt);
router.post("/searchProductByInput", searchProductByInput);
router.get("/getMopSettings", getMopSettings);
router.post("/setMopSettings", setMopSettings);
router.post("/addPurchaseInvoice", addPurchaseInvoice);
router.post("/addSalesInvoice", addSalesInvoice);
router.get("/getTrialBalanceSimpleData", getTrialBalanceSimpleData);
router.get("/getTrialBalanceDetailedData", getTrialBalanceDetailedData);
router.get("/getProfitAndLossSimpleData", getProfitAndLossSimpleData);
router.get("/getProfitAndLossDetailedData", getProfitAndLossDetailedData);
router.get("/getBalanceSheetSimpleData", getBalanceSheetSimpleData);
router.get("/getBalanceSheetDetailedData", getBalanceSheetDetailedData);
router.get("/getPurchaseDayBookData", getPurchaseDayBookData);
router.get("/getPurchaseDayBookDetailData", getPurchaseDayBookDetailData);
router.get("/getSalesDayBookData", getSalesDayBookData);
router.get("/getSalesDayBookDetailData", getSalesDayBookDetailData);
router.get("/getBanks", getBanks);
router.post("/uploadCustomers", uploadCustomers);
router.post("/uploadVendors", uploadVendors);
router.post("/getOsByAccountCode", getOsByAccountCode);
router.get("/getledgerReportData", getledgerReportData);
router.post("/searchCustomerLedgersByInput", searchCustomerLedgersByInput);
router.get("/getOutstandingCustomerData", getOutstandingCustomerData);
router.get("/getInvoiceHeaderData", getInvoiceHeaderData);
router.get("/getInvoiceItemsData", getInvoiceItemsData);
router.get("/getInvoiceFooterData", getInvoiceFooterData);
router.get("/getPaymentReportData", getPaymentReportData);
router.get("/getReceiptReportData", getReceiptReportData);
router.post("/internalLoginToFormat", internalLoginToFormat);
router.post("/internalLoginToDelInvoice", internalLoginToDelInvoice);
router.post("/uploadProductCategories", uploadProductCategories);
router.post("/uploadProductDetails", uploadProductDetails);
router.get("/getProfile", getProfile);
router.post("/updateProfile", updateProfile);
router.post("/changePassword", changePassword);
router.post("/uploadLogo", uploadLogo);
router.post("/addSalesOrderInvoice", addSalesOrderInvoice);
router.get("/getSalesOrderDayBookData", getSalesOrderDayBookData);
router.get("/getSalesOrderDayBookDetailData", getSalesOrderDayBookDetailData);
router.post("/convertToSales", convertToSales);
router.post("/addStore", addStore);
router.post("/updateStore", updateStore);
router.get("/getStoresData", getStoresData);
router.get("/getStoreById", getStoreById);
router.post("/delStore", delStore);
router.post("/uploadStores", uploadStores);
router.get("/getStores", getStores);
router.post("/addStockTransferInvoice", addStockTransferInvoice);
router.get("/getStockTransferHeaderData", getStockTransferHeaderData);
router.get("/getStockTransferFooterData", getStockTransferFooterData);
router.get("/getStockTransferItemsData", getStockTransferItemsData);
router.get("/getStockTransferDayBookData", getStockTransferDayBookData);
router.get(
  "/getStockTransferDayBookDetailData",
  getStockTransferDayBookDetailData
);
router.get("/getStocksReportData", getStocksReportData);
router.post("/searchStoresByInput", searchStoresByInput);
router.get("/getPurchaseItemWiseData", getPurchaseItemWiseData);
router.get("/getSalesItemWiseData", getSalesItemWiseData);
router.get("/getSalesOrderItemWiseData", getSalesOrderItemWiseData);
router.get("/getStockTransferItemWiseData", getStockTransferItemWiseData);
router.post("/addRole", addRole);
router.post("/updateRole", updateRole);
router.get("/getRoles", getRoles);
router.get("/getRoleById", getRoleById);
router.post("/delRole", delRole);
router.post("/uploadRoles", uploadRoles);
router.post("/addUser", addUser);
//post http://localhost:5000/api/addUser
router.post("/updateUser", updateUser);
//post http://localhost:5000/api/updateUser
router.get("/getUsers", getUsers);
//post http://localhost:5000/api/getUser
router.get("/getUserById", getUserById);
//post http://localhost:5000/api/getUserById
router.post("/delUsers", delUsers);
//post http://localhost:5000/api/delUsers
router.post("/uploadUsers", uploadUsers);
router.post("/addPage", addPage);
router.post("/updatePage", updatePage);
router.get("/getPages", getPages);
router.get("/getPageById", getPageById);
router.post("/uploadPages", uploadPages);
router.post("/getPermissionsById", getPermissionsById);
router.post("/updatePermission", updatePermission);
router.post("/uploadQRImage", uploadQRImage);
router.get("/getSalesGraphData", getSalesGraphData);
router.get("/searchAdmins", searchAdmins);
router.get("/searchUsername", searchUsername);
router.post("/sendEmailOTP", sendEmailOTP);
router.post("/verifyEmailOTP", verifyEmailOTP);
router.post("/adminSignUp", adminSignUp);
router.get("/getBarcodeSeries", getBarcodeSeries);
router.post("/searchSalesProductByInput", searchSalesProductByInput);
router.post("/searchBarcodeByInput", searchBarcodeByInput);
router.post("/validateBarcodeInStock", validateBarcodeInStock);
router.post("/addOpeningStockInvoice", addOpeningStockInvoice);
router.get("/getOpeningStockDayBookData", getOpeningStockDayBookData);
router.get(
  "/getOpeningStockDayBookDetailData",
  getOpeningStockDayBookDetailData
);
router.get("/getOpeningStockItemWiseData", getOpeningStockItemWiseData);
router.post("/sendEmailLinkToResetPassword", sendEmailLinkToResetPassword);
router.post("/sendPasswordToReset", sendPasswordToReset);
router.post("/uploadProductItemsDetails", uploadProductItemsDetails);
router.post("/uploadSalesProductItemsDetails", uploadSalesProductItemsDetails);
router.post(
  "/uploadSalesReturnProductItemsDetails",
  uploadSalesReturnProductItemsDetails
);
router.post("/addImportStock", addImportStock);
router.post("/searchUserByInput", searchUserByInput);
router.get("/getCountries", getCountries);
router.get("/getStates", getStates);
router.get("/getCities", getCities);
router.get("/getNextVerifiedInvoiceNo", getNextVerifiedInvoiceNo);
router.get("/getOutstandingUserStatement", getOutstandingUserStatement);
router.post("/addEstimateInvoice", addEstimateInvoice);
router.get("/getEstimateDayBookData", getEstimateDayBookData);
router.get("/getEstimateDayBookDetailData", getEstimateDayBookDetailData);
router.get("/getEstimateItemWiseData", getEstimateItemWiseData);
router.get("/getledgerSummarisedReportData", getledgerSummarisedReportData);
router.get(
  "/getledgerSummarisedBalanceSheetData",
  getledgerSummarisedBalanceSheetData
);
router.get("/getInvoiceSeriesForCustomer", getInvoiceSeriesForCustomer);
router.post("/addDynamicColumns", addDynamicColumns);
router.get("/getPriceLists", getPriceLists);
router.get("/getPriceListById", getPriceListById);
router.post("/delPriceList", delPriceList);
router.post("/updateDynamicColumns", updateDynamicColumns);
router.post("/updateAllProductDetails", updateAllProductDetails);
router.post("/addPettySalesInvoice", addPettySalesInvoice);
router.get("/getPettySalesDayBookData", getPettySalesDayBookData);
router.get("/getPettySalesDayBookDetailData", getPettySalesDayBookDetailData);
router.get("/getPettySalesItemWiseData", getPettySalesItemWiseData);
router.get("/getReceiptByInvoiceNo", getReceiptByInvoiceNo);
router.get("/getPaymentByInvoiceNo", getPaymentByInvoiceNo);
router.post("/getOsByDefaultAccountCode", getOsByDefaultAccountCode);
router.post("/searchProductCategoryByInput", searchProductCategoryByInput);
router.post(
  "/searchProductByProductCategoryByInput",
  searchProductByProductCategoryByInput
);
router.get("/getReceiptSplitsData", getReceiptSplitsData);
router.get("/getPaymentSplitsData", getPaymentSplitsData);
router.get("/getBillByBillCustomerData", getBillByBillCustomerData);
router.get("/getBillByBillSupplierData", getBillByBillSupplierData);
router.get(
  "/getAgeingWiseOutstandingUserStatement",
  getAgeingWiseOutstandingUserStatement
);
router.get("/getStockHistoryReportData", getStockHistoryReportData);
router.post("/addPurchaseReturnInvoice", addPurchaseReturnInvoice);
router.get("/getPurchaseReturnDayBookData", getPurchaseReturnDayBookData);
router.get(
  "/getPurchaseReturnDayBookDetailData",
  getPurchaseReturnDayBookDetailData
);
router.get("/getPurchaseReturnItemWiseData", getPurchaseReturnItemWiseData);
router.post("/addSalesReturnInvoice", addSalesReturnInvoice);
router.get("/getSalesReturnDayBookData", getSalesReturnDayBookData);
router.get("/getSalesReturnDayBookDetailData", getSalesReturnDayBookDetailData);
router.get("/getSalesReturnItemWiseData", getSalesReturnItemWiseData);
router.get("/getSalesReturnInvoiceData", getSalesReturnInvoiceData);
router.post("/addProductionInvoice", addProductionInvoice);
router.post(
  "/searchBarcodeByInputForStocksReport",
  searchBarcodeByInputForStocksReport
);
router.post("/uploadCompanySealImage", uploadCompanySealImage);
router.post("/uploadAuthorisedSignatureImage", uploadAuthorisedSignatureImage);
router.get("/getProductCompositionData", getProductCompositionData);
router.get("/getProductCompositionById", getProductCompositionById);
router.post("/updateProductComposition", updateProductComposition);
router.post("/addProductComposition", addProductComposition);
router.post("/delProductComposition", delProductComposition);

router.post("/createAttendance", addAttendance.addAttendances); 
router.post("/deleteAttendance", deleteAttendance.deleteAttendance);
router.get("/getAllAttendances", getAllAttendance.getAllAttendances);  
router.post("/updateAttendance", updateAttendance.updateAttendance);
router.get("/attendance/salarybalance/:userId", getSalaryBalance); 

//new Route 

router.post("/addOrEditPrnFile" , addOrEditPrnFile)

module.exports = router;
